# Generated by Django 5.2.3 on 2025-06-25 01:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Nueva conversación', max_length=200)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_ultima_actividad', models.DateTimeField(default=django.utils.timezone.now)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-fecha_ultima_actividad'],
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('usuario', 'Usuario'), ('bot', 'Bot')], max_length=10)),
                ('contenido', models.TextField()),
                ('sql_generado', models.TextField(blank=True, null=True)),
                ('resultados_json', models.JSONField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='chat.conversacion')),
            ],
            options={
                'ordering': ['fecha_creacion'],
            },
        ),
    ]
